CREATE TABLE todo
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR(255),
    description VARCHAR(255),
    checked     BOOLEAN,
    created_at  date,
    CONSTRAINT pk_todo PRIMARY KEY (id)
);